name: cleaneo_vendor
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_localization: ^0.2.0
  intl: ^0.18.1
  flutter_svg: ^2.0.9
  intl_phone_number_input: ^0.7.4
  country_code_picker: ^3.0.0
  flutter_profile_picture: ^2.0.0
  image_picker: ^1.0.7
  pin_code_fields: ^7.3.0
  pinput: ^3.0.1
  shared_preferences: ^2.2.2
  flutter_rating_bar: ^4.0.1
  font_awesome_flutter: ^10.7.0
  flutter_localizations:
    sdk: flutter
  url_launcher: ^6.2.5
  flutter_switch: ^0.3.2
  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/images/drawer-images/
    - assets/images/
    - assets/onboarding/
    - assets/images/Home/

  fonts:
    - family: PoppinsBlack
      fonts:
        - asset: assets/Fonts/Poppins-Black.ttf
    - family: PoppinsBold
      fonts:
        - asset: assets/Fonts/Poppins-Bold.ttf
    - family: PoppinsExtraBold
      fonts:
        - asset: assets/Fonts/Poppins-ExtraBold.ttf
    - family: PoppinsExtraLight
      fonts:
        - asset: assets/Fonts/Poppins-ExtraLight.ttf
    - family: PoppinsLight
      fonts:
        - asset: assets/Fonts/Poppins-Light.ttf
    - family: PoppinsMedium
      fonts:
        - asset: assets/Fonts/Poppins-Medium.ttf
    - family: PoppinsRegular
      fonts:
        - asset: assets/Fonts/Poppins-Regular.ttf
    - family: PoppinsSemiBold
      fonts:
        - asset: assets/Fonts/Poppins-SemiBold.ttf
    - family: PoppinsThin
      fonts:
        - asset: assets/Fonts/Poppins-Thin.ttf
